week_6/asset_pipeline/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/sport'

  get 'pages/muic'

  get 'pages/gossip'

  get 'pages/contact'

  root 'pages#home'

end

week_6/asset_pipeline/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week_6/asset_pipeline/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sport
  end

  def muic
  end

  def gossip
  end

  def contact
  end
end

week_6/asset_pipeline/app/helpers/application_helper.rb
module ApplicationHelper
end

week_6/asset_pipeline/app/helpers/pages_helper.rb
module PagesHelper
end

week_6/asset_pipeline/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssetPipeline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
 <header>
    <nav>
      <li><%= link_to('HOME', root_path) %></li>
      <li><%= link_to('MUSIC', pages_muic_path) %></li>
      <li><%= link_to('GOSSIP', pages_gossip_path) %></li>
      <li><%= link_to('SPORT', pages_sport_path) %></li>
    </nav>
  </header>
  <%= yield %>
</div>


</body>
</html>

week_6/asset_pipeline/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

week_6/asset_pipeline/app/views/pages/gossip.html.erb
<h1>Pages#gossip</h1>
<p>Find me in app/views/pages/gossip.html.erb</p>

week_6/asset_pipeline/app/views/pages/home.html.erb
<div class="homepage-container">
  <%= image_tag('saudi.jpg') %>
<div class="homepage-content">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam cum magni distinctio, voluptatem corrupti dolorum sed molestiae, aspernatur sapiente perferendis enim iure quis quos iste necessitatibus culpa. Enim soluta, autem!</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates alias maxime eum, eveniet consequatur sapiente doloremque illo reiciendis, laboriosam, molestiae porro vero voluptatibus, doloribus repellendus dolores quo. Perferendis, hic, id.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates alias maxime eum, eveniet consequatur sapiente doloremque illo reiciendis, laboriosam, molestiae porro vero voluptatibus, doloribus repellendus dolores quo. Perferendis, hic, id.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates alias maxime eum, eveniet consequatur sapiente doloremque illo reiciendis</p>

</div>
</div>

week_6/asset_pipeline/app/views/pages/muic.html.erb
<h1>Pages#muic</h1>
<p>Find me in app/views/pages/muic.html.erb</p>

week_6/asset_pipeline/app/views/pages/sport.html.erb
<h1>Pages#sport</h1>
<p>Find me in app/views/pages/sport.html.erb</p>